SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE route_ratings;
TRUNCATE TABLE user_saved_routes;
TRUNCATE TABLE itinerary_activities;
TRUNCATE TABLE route_itinerary;
TRUNCATE TABLE recommended_routes;
TRUNCATE TABLE route_preferences;
TRUNCATE TABLE trip_themes;
TRUNCATE TABLE survey_answers;
TRUNCATE TABLE survey_options;
TRUNCATE TABLE survey_questions;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO trip_themes (theme_id, theme_name, theme_description) VALUES (1, 'K-pop & Hallyu', 'K-pop과 한류 관련 여행');
INSERT INTO trip_themes (theme_id, theme_name, theme_description) VALUES (2, 'Food Tour', '음식 중심 여행');
INSERT INTO trip_themes (theme_id, theme_name, theme_description) VALUES (3, 'History & Culture', '역사·문화 탐방');
INSERT INTO trip_themes (theme_id, theme_name, theme_description) VALUES (4, 'Nature & Healing', '자연·힐링 여행');
INSERT INTO trip_themes (theme_id, theme_name, theme_description) VALUES (5, 'Shopping', '쇼핑 중심 여행');
INSERT INTO trip_themes (theme_id, theme_name, theme_description) VALUES (6, 'City Tour', '도시 관광');
INSERT INTO trip_themes (theme_id, theme_name, theme_description) VALUES (7, 'Adventure', '액티비티·체험 여행');

INSERT INTO survey_questions (id, question_key, question_type, question_ko, question_en, question_ja, question_zh) VALUES (1, 'travel_style', 'single', '어떤 여행 스타일을 선호하시나요?', 'What is your preferred travel style?', '旅行スタイルは？', '您偏好哪种旅行风格？');
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (1, 'relaxed', '여유롭게', 'Relaxed', 'ゆっくり', '悠闲', 1);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (1, 'packed', '빽빽하게', 'Packed', 'びっしり', '紧凑', 2);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (1, 'balanced', '적당히', 'Balanced', 'バランス', '适中', 3);
INSERT INTO survey_questions (id, question_key, question_type, question_ko, question_en, question_ja, question_zh) VALUES (2, 'companion', 'single', '누구와 여행하시나요?', 'Who are you traveling with?', '誰と旅行しますか？', '您和谁一起旅行？');
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (2, 'solo', '혼자', 'Solo', '一人旅', '独自', 1);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (2, 'friend', '친구와', 'With friends', '友達と', '和朋友', 2);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (2, 'family', '가족과', 'With family', '家族と', '和家人', 3);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (2, 'couple', '연인과', 'With partner', '恋人と', '和伴侣', 4);
INSERT INTO survey_questions (id, question_key, question_type, question_ko, question_en, question_ja, question_zh) VALUES (3, 'interest', 'multi', '관심 있는 테마를 선택하세요', 'Select themes you are interested in', '興味のあるテーマを選んでください', '请选择感兴趣的主题');
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (3, 'kpop', 'K-pop·한류', 'K-pop & Hallyu', 'K-pop・韓流', 'K-pop·韩流', 1);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (3, 'food', '맛집·음식', 'Food Tour', 'グルメ', '美食', 2);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (3, 'history', '역사·문화', 'History', '歴史・文化', '历史文化', 3);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (3, 'nature', '자연·힐링', 'Nature', '自然・癒し', '自然', 4);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (3, 'shopping', '쇼핑', 'Shopping', 'ショッピング', '购物', 5);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (3, 'cafe', '카페·디저트', 'Cafe & Dessert', 'カフェ', '咖啡', 6);
INSERT INTO survey_questions (id, question_key, question_type, question_ko, question_en, question_ja, question_zh) VALUES (4, 'transport', 'single', '이동 수단을 선택하세요', 'Select your transport mode', '移動手段を選んでください', '请选择交通方式');
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (4, 'public', '대중교통', 'Public Transit', '公共交通', '公共交通', 1);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (4, 'walk', '도보', 'Walking', '徒歩', '步行', 2);
INSERT INTO survey_options (question_id, option_key, option_ko, option_en, option_ja, option_zh, sort_order) VALUES (4, 'taxi', '택시·차', 'Taxi / Car', 'タクシー', '出租车', 3);