SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE place_theme DROP FOREIGN KEY fk_pt_place;
ALTER TABLE place_theme MODIFY COLUMN place_id VARCHAR(20) NOT NULL;
ALTER TABLE places MODIFY COLUMN place_id VARCHAR(20) NOT NULL;
ALTER TABLE place_theme ADD CONSTRAINT fk_pt_place 
    FOREIGN KEY (place_id) REFERENCES places(place_id) ON DELETE CASCADE;

SET FOREIGN_KEY_CHECKS=1;